version: '3.8'

services:
  moodle-db:
    image: mariadb:${MARIADB_VERSION}
    container_name: moodle-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - moodle-db-data:/var/lib/mysql
    networks:
      - moodle-net

  moodle:
    build: ./moodle  # O usa image: moodle-docker-moodle:latest si ya la tienes
    container_name: moodle
    restart: always
    depends_on:
      - moodle-db
    environment:
      MOODLE_DBTYPE: ${MOODLE_DBTYPE}
      MOODLE_DBHOST: ${MOODLE_DBHOST}
      MOODLE_DBNAME: ${MOODLE_DBNAME}
      MOODLE_DBUSER: ${MOODLE_DBUSER}
      MOODLE_DBPASS: ${MOODLE_DBPASS}
      MOODLE_USERNAME: ${MOODLE_USERNAME}
      MOODLE_PASSWORD: ${MOODLE_PASSWORD}
      MOODLE_SITE_NAME: ${MOODLE_SITE_NAME}
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - moodle-data:/var/www/html
    networks:
      - moodle-net

volumes:
  moodle-db-data:
  moodle-data:

networks:
  moodle-net:
  